# Generated by Django 4.0.6 on 2022-07-20 23:47

from django.db import migrations, models
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=13, validators=[utils.validators.validate_length, utils.validators.validate_is_digits_inside, utils.validators.validate_is_latin_letters], verbose_name='word')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
