# Generated by Django 4.0.6 on 2022-07-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=10, verbose_name='word'),
        ),
    ]
