# Generated by Django 4.0.6 on 2022-07-17 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinValueValidator(2)], verbose_name='word'),
        ),
    ]
