# Generated by Django 4.0.6 on 2022-07-18 20:47

from django.db import migrations, models
import guess_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('guess_app', '0003_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=13, validators=[guess_app.validators.validate_length, guess_app.validators.validate_is_digits_inside], verbose_name='word'),
        ),
    ]
