version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: heyaslan/guess_word:v1.1.3
    restart: always
    depends_on:
      - db
      - cache
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend:/usr/share/nginx/
      - static_value:/var/html/static/
    depends_on:
      - web
      - db

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data


volumes:
  postgres_data:
  static_value:
  cache:
